
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mic
 */
public class BB extends javax.swing.JFrame {
    String temp = "";
    Double bi,tb,bb;

    /**
     * Creates new form BB
     */
    public BB() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        l = new javax.swing.JRadioButton();
        w = new javax.swing.JRadioButton();
        hitung = new javax.swing.JButton();
        cobalagi = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        hbi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        h1 = new javax.swing.JTextField();
        h2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(157, 11, 87, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(75, 51, 27, 14);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(74, 89, 28, 14);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(43, 127, 59, 14);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(39, 166, 63, 14);
        getContentPane().add(n);
        n.setBounds(120, 48, 160, 20);
        getContentPane().add(t);
        t.setBounds(120, 86, 160, 20);
        getContentPane().add(b);
        b.setBounds(120, 124, 160, 20);

        buttonGroup1.add(l);
        l.setText("Laki-laki");
        getContentPane().add(l);
        l.setBounds(120, 162, 63, 23);

        buttonGroup1.add(w);
        w.setText("Perempuan");
        getContentPane().add(w);
        w.setBounds(201, 162, 79, 23);

        hitung.setForeground(new java.awt.Color(0, 204, 204));
        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(73, 203, 63, 23);

        cobalagi.setForeground(new java.awt.Color(0, 204, 204));
        cobalagi.setText("Coba lagi");
        cobalagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobalagiActionPerformed(evt);
            }
        });
        getContentPane().add(cobalagi);
        cobalagi.setBounds(154, 203, 77, 23);

        exit.setForeground(new java.awt.Color(0, 204, 204));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(241, 203, 51, 23);

        hbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbiActionPerformed(evt);
            }
        });
        getContentPane().add(hbi);
        hbi.setBounds(241, 237, 44, 20);

        jLabel6.setText("Kg");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(289, 240, 12, 14);

        jLabel7.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(85, 240, 146, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 255));
        jLabel8.setText("Hasil diagnosa kesehatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(105, 268, 154, 15);

        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });
        getContentPane().add(h1);
        h1.setBounds(39, 289, 320, 20);

        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });
        getContentPane().add(h2);
        h2.setBounds(39, 315, 320, 20);

        setBounds(0, 0, 416, 433);
    }// </editor-fold>//GEN-END:initComponents

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h1ActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h2ActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        if(b.getText().equals("")||t.getText().equals("")||n.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kotak isian Belum diisi, maka harus diisi");
        }else if (w.isSelected()||l.isSelected())
            try{
                Proses();
            }
        catch(Exception e) {
           JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
        }
        else {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin silahkan diisi");
        }
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_hitungActionPerformed

    private void hbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hbiActionPerformed

    private void cobalagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobalagiActionPerformed
        n.setText("");
        t.setText("");
        b.setText("");
        buttonGroup1.clearSelection();
        hbi.setText("");
        h1.setText("");
        h2.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_cobalagiActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cobalagi;
    private javax.swing.JButton exit;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField hbi;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton l;
    private javax.swing.JTextField n;
    private javax.swing.JTextField t;
    private javax.swing.JRadioButton w;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        tb = Double.valueOf(t.getText());
        bb = Double.valueOf(b.getText());
        
        if(w.isSelected()){
            bi = (tb -110) * 1;
        } else if (l.isSelected()) {
            bi = (tb - 104) * 1;
        }
        temp = Double.toString(bi.intValue());
        if(bi <bb) 
        {
            hbi.setText(temp);
            h1.setText("Maaf "+n.getText()+",Sepertinya Anda Overweight :(");
            h2.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        }else if (bi>bb) {
            hbi.setText(temp);
            h1.setText("Maaf "+n.getText()+",Sepertinya Anda Underweight :(");
            h2.setText("Banyaklah berolahraga dan hindari makanan berkarbohidrat");
        }else {
            hbi.setText(temp);
            h1.setText("Yaa "+n.getText()+",Sepertinya Anda sudah ideal :(");
            h2.setText("Lanjutkan pola makan teratur dan gaya hidup sehat");
    }}
}
