/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Frame4 extends javax.swing.JFrame {

    /**
     * Creates new form Frame4
     */
    public Frame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        rdb2 = new javax.swing.JButton();
        rdb3 = new javax.swing.JButton();
        rdb1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biodata Siswa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 0, 100, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 40, 50, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Absen");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 50, 20);
        jPanel1.add(Nama);
        Nama.setBounds(100, 30, 170, 30);
        jPanel1.add(Absen);
        Absen.setBounds(100, 70, 170, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jurusan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 114, 50, 20);

        btnGroup.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(0, 153, 153));
        jRadioButton1.setText("RPL");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(100, 110, 60, 30);

        btnGroup.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(0, 153, 153));
        jRadioButton2.setText("TKJ");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(180, 110, 60, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hobi");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 150, 40, 20);

        cb1.setForeground(new java.awt.Color(0, 153, 153));
        cb1.setText("Programmer");
        jPanel1.add(cb1);
        cb1.setBounds(100, 153, 90, 30);

        cb2.setForeground(new java.awt.Color(0, 153, 153));
        cb2.setText("Designer");
        jPanel1.add(cb2);
        cb2.setBounds(100, 190, 90, 30);

        cb3.setForeground(new java.awt.Color(0, 153, 153));
        cb3.setText("Teknisi");
        jPanel1.add(cb3);
        cb3.setBounds(210, 150, 100, 30);

        cb4.setForeground(new java.awt.Color(0, 153, 153));
        cb4.setText("Developper");
        jPanel1.add(cb4);
        cb4.setBounds(210, 190, 100, 30);

        rdb2.setForeground(new java.awt.Color(0, 153, 153));
        rdb2.setText("Hapus");
        rdb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb2ActionPerformed(evt);
            }
        });
        jPanel1.add(rdb2);
        rdb2.setBounds(173, 240, 100, 23);

        rdb3.setForeground(new java.awt.Color(0, 153, 153));
        rdb3.setText("Keluar");
        rdb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb3ActionPerformed(evt);
            }
        });
        jPanel1.add(rdb3);
        rdb3.setBounds(290, 240, 90, 23);

        rdb1.setForeground(new java.awt.Color(0, 153, 153));
        rdb1.setText("Submit");
        rdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb1ActionPerformed(evt);
            }
        });
        jPanel1.add(rdb1);
        rdb1.setBounds(65, 240, 90, 23);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 280, 270, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 440);

        setBounds(0, 0, 453, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void rdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb1ActionPerformed
       String nama = Nama.getText();
       int absen = Integer.parseInt(Absen.getText());
       String jurusan;
       String hobi = "";
       
       if(rdb1.isSelected())
           jurusan = "RPL";
       else if(rdb2.isSelected())
           jurusan = "TKJ";
       else
           jurusan = "";
       
       if(cb1.isSelected())
           hobi+=cb1.getText()+" ";
       if(cb2.isSelected())
           hobi+=cb2.getText()+" ";
       if(cb3.isSelected())
           hobi+=cb3.getText()+" ";
       if(cb4.isSelected())
           hobi+=cb4.getText()+" ";
       
       TA.setText("Nama :"+nama+"\nAbsen :"+absen+"\nJurusan :"+jurusan+"\nHobi :"+hobi);
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb1ActionPerformed

    private void rdb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb2ActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Absen.setText("");
        TA.setText("");
        cb1.setSelected(false);
        cb2.setSelected(false);
        cb3.setSelected(false);
        cb4.setSelected(false);
        btnGroup.clearSelection();
    }//GEN-LAST:event_rdb2ActionPerformed

    private void rdb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_rdb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextArea TA;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rdb1;
    private javax.swing.JButton rdb2;
    private javax.swing.JButton rdb3;
    // End of variables declaration//GEN-END:variables
}
