/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Frame6 extends javax.swing.JFrame {

    /**
     * Creates new form Frame6
     */
    public Frame6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nilai = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        mapel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setText("Hasil");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 280, 90, 30);

        jLabel2.setText("Absen");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 90, 150, 30);

        jLabel3.setText("Penilaian");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 0, 150, 30);

        jLabel4.setText("Nama");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 50, 150, 30);

        jLabel5.setText("Mata Pelajaran");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 130, 150, 30);

        jLabel6.setText("Nilai");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 170, 150, 30);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 220, 80, 30);
        jPanel1.add(nilai);
        nilai.setBounds(170, 170, 220, 30);
        jPanel1.add(nama);
        nama.setBounds(170, 50, 220, 30);
        jPanel1.add(absen);
        absen.setBounds(170, 90, 220, 30);
        jPanel1.add(mapel);
        mapel.setBounds(170, 130, 220, 30);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 270, 240, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 430, 430);

        setBounds(0, 0, 444, 469);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Nama = nama.getText();
        int Absen = Integer.parseInt(absen.getText());
        String Mapel = mapel.getText();
        int Nilai = Integer.parseInt(nilai.getText());
        
        Hasil.append("Nama : " + Nama + "\n No Absen : " + Absen + "\n MaPel : " + Mapel + "\n Predikat : " + Nilai);
        if (Nilai >= 86 && Nilai <= 100){
                Hasil.append("Selamat nilai anda sempurna");
            }
            else if (Nilai >=75 && Nilai <= 85){
                Hasil.append("Anda lulus");
            }
            else if (Nilai <=74){
                Hasil.append("Anda tidak lulus");
            }
            else{
                Hasil.append("pastikan nilai anda benar");
            }   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Hasil;
    private javax.swing.JTextField absen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mapel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilai;
    // End of variables declaration//GEN-END:variables
}
